libraries:
  Babel: 2.11.0
  Bottleneck: 1.3.7
  Brotli: 1.0.9
  Jinja2: 3.1.3
  Keras-Preprocessing: 1.1.2
  Markdown: 3.4.1
  MarkupSafe: 2.1.3
  PyJWT: 2.4.0
  PyQt5: 5.15.10
  PyQt5-sip: 12.13.0
  PySocks: 1.7.1
  PyYAML: 6.0.1
  Pygments: 2.15.1
  QtPy: 2.4.1
  Send2Trash: 1.8.2
  Werkzeug: 2.3.8
  absl-py: 2.1.0
  aiohttp: 3.9.3
  aiosignal: 1.2.0
  anyio: 4.2.0
  appnope: 0.1.2
  argon2-cffi: 21.3.0
  argon2-cffi-bindings: 21.2.0
  asttokens: 2.0.5
  astunparse: 1.6.3
  async-lru: 2.0.4
  async-timeout: 4.0.3
  attrs: 23.1.0
  backcall: 0.2.0
  beautifulsoup4: 4.12.2
  bleach: 4.1.0
  blinker: 1.6.2
  cachetools: 5.3.3
  certifi: 2024.2.2
  cffi: 1.16.0
  charset-normalizer: 2.0.4
  click: 8.1.7
  comm: 0.2.1
  contourpy: 1.0.5
  cryptography: 41.0.3
  cycler: 0.11.0
  debugpy: 1.6.7
  decorator: 5.1.1
  defusedxml: 0.7.1
  exceptiongroup: 1.2.0
  executing: 0.8.3
  fastjsonschema: 2.16.2
  flatbuffers: '2.0'
  fonttools: 4.51.0
  frozenlist: 1.4.0
  gast: 0.4.0
  google-ai-generativelanguage: 0.1.0
  google-api-core: 2.19.0
  google-auth: 2.29.0
  google-auth-oauthlib: 0.4.4
  google-generativeai: 0.1.0rc1
  google-pasta: 0.2.0
  googleapis-common-protos: 1.63.0
  grpcio: 1.63.0
  grpcio-status: 1.62.2
  h5py: 3.9.0
  idna: '3.7'
  importlib-metadata: 7.0.1
  importlib-resources: 6.1.1
  ipykernel: 6.28.0
  ipython: 8.12.2
  ipywidgets: 8.1.2
  jedi: 0.18.1
  joblib: 1.4.0
  json5: 0.9.6
  jsonschema: 4.19.2
  jsonschema-specifications: 2023.7.1
  jupyter: 1.0.0
  jupyter-console: 6.6.3
  jupyter-events: 0.8.0
  jupyter-lsp: 2.2.0
  jupyter_client: 8.6.0
  jupyter_core: 5.5.0
  jupyter_server: 2.10.0
  jupyter_server_terminals: 0.4.4
  jupyterlab: 4.0.11
  jupyterlab-pygments: 0.1.2
  jupyterlab-widgets: 3.0.10
  jupyterlab_server: 2.25.1
  keras: 2.10.0
  kiwisolver: 1.4.4
  matplotlib: 3.7.2
  matplotlib-inline: 0.1.6
  mistune: 2.0.4
  mkl-fft: 1.3.1
  mkl-random: 1.2.2
  mkl-service: 2.4.0
  multidict: 6.0.4
  nbclient: 0.8.0
  nbconvert: 7.10.0
  nbformat: 5.9.2
  nest-asyncio: 1.6.0
  notebook: 7.0.8
  notebook_shim: 0.2.3
  numexpr: 2.8.4
  numpy: 1.24.3
  oauthlib: 3.2.2
  opt-einsum: 3.3.0
  overrides: 7.4.0
  packaging: '23.2'
  pandas: 2.0.3
  pandocfilters: 1.5.0
  parso: 0.8.3
  pexpect: 4.8.0
  pickleshare: 0.7.5
  pillow: 10.3.0
  pip: 23.3.1
  pkgutil_resolve_name: 1.3.10
  platformdirs: 3.10.0
  ply: '3.11'
  pooch: 1.7.0
  prometheus-client: 0.14.1
  prompt-toolkit: 3.0.43
  proto-plus: 1.23.0
  protobuf: 4.25.3
  psutil: 5.9.0
  ptyprocess: 0.7.0
  pure-eval: 0.2.2
  pyOpenSSL: 23.2.0
  pyasn1: 0.4.8
  pyasn1-modules: 0.2.8
  pycparser: '2.21'
  pyparsing: 3.0.9
  python-dateutil: 2.8.2
  python-json-logger: 2.0.7
  pytz: '2024.1'
  pyzmq: 25.1.2
  qtconsole: 5.5.1
  referencing: 0.30.2
  requests: 2.31.0
  requests-oauthlib: 1.3.0
  rfc3339-validator: 0.1.4
  rfc3986-validator: 0.1.1
  rpds-py: 0.10.6
  rsa: 4.7.2
  scikit-learn: 1.2.2
  scipy: 1.10.0
  setuptools: 68.2.2
  sip: 6.7.12
  six: 1.16.0
  sniffio: 1.3.0
  soupsieve: '2.5'
  stack-data: 0.2.0
  tensorboard: 2.10.0
  tensorboard-data-server: 0.6.1
  tensorboard-plugin-wit: 1.6.0
  tensorflow: 2.10.0
  tensorflow-estimator: 2.10.0
  termcolor: 2.1.0
  terminado: 0.17.1
  threadpoolctl: 2.2.0
  tinycss2: 1.2.1
  tomli: 2.0.1
  tornado: 6.3.3
  traitlets: 5.7.1
  typing_extensions: 4.9.0
  tzdata: '2023.3'
  unicodedata2: 15.1.0
  urllib3: 2.1.0
  wcwidth: 0.2.5
  webencodings: 0.5.1
  websocket-client: 0.58.0
  wheel: 0.35.1
  widgetsnbextension: 4.0.10
  wrapt: 1.14.1
  yarl: 1.9.3
  zipp: 3.17.0
